### PR TITLE
fix: decode html special chars for mailto link

### LINKED ISSUE #2194: Application email subject uses `&quot;` instead of `"`
This bug is fixed by #2187

**Describe the bug**
When you're on the job detail page and click on the mailto link the mail subject can include html entities.
This can be seen particularly clearly when WordPress is set to German, as here the translation already uses `"`, which is then displayed as `&quot` in the mail subject.

```po
#. translators: %1$s is the job listing title; %2$s is the URL for the current
#. WordPress instance.
#: wp-job-manager-template.php:249
msgid "Application via %1$s listing on %2$s"
msgstr "Bewerbung zum Jobangebot \"%1$s\" auf %2$s"
```

**To Reproduce**
1. Create a job with any title, I'll use `demo`
2. Set the WordPress language to germen
3. View the job in the frontend
4. Apply via e-mail
5. See that the subject says `Bewerbung zum Jobangebot &quot;demo&quot; auf https://example.com`

**Expected behavior**
html entities should be encoded for the mail subject

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.8.1
- WP Job Manager Version: 1.35.2
- PHP Version: 7.4

### PR DESCRIPTION
**Pull request by RafaelKr**
fixes #2194

The german translation for the email subject includes quotes around the job name.

```po
#. translators: %1$s is the job listing title; %2$s is the URL for the current
#. WordPress instance.
#: wp-job-manager-template.php:249
msgid "Application via %1$s listing on %2$s"
msgstr "Bewerbung zum Jobangebot \"%1$s\" auf %2$s"
```

In the email subject this was inserted as `&quot;` instead of `"`. This commit uses htmlspecialchars_decode to fix that.

### CODE REVIEW

File: templates/job-application-email.php [hunk 1]
```diff
@@ -16,4 +16,4 @@
 }
 ?>
 <?php // translators: %1$s is the email address, %2$s is the subject query args. ?>
-<p><?php printf( wp_kses_post( __( 'To apply for this job <strong>email your details to</strong> <a class="job_application_email" href="mailto:%1$s%2$s">%1$s</a>', 'wp-job-manager' ) ), esc_html( $apply->email ), '?subject=' . rawurlencode( $apply->subject ) ); ?></p>
+<p><?php printf( wp_kses_post( __( 'To apply for this job <strong>email your details to</strong> <a class="job_application_email" href="mailto:%1$s%2$s">%1$s</a>', 'wp-job-manager' ) ), esc_html( $apply->email ), '?subject=' . rawurlencode( htmlspecialchars_decode( $apply->subject ) ) ); ?></p>
```
Comment (fjorgemota) [inline templates/job-application-email.php:19]: This is a very small detail, but..could you please change `htmlspecialchars_decode` to [`wp_specialchars_decode`](https://developer.wordpress.org/reference/functions/wp_specialchars_decode/)? I feel it should be more appropriate for the task, especially as it's a WordPress function that does basically the same task.

Here's my suggestion:

```suggestion
<p><?php printf( wp_kses_post( __( 'To apply for this job <strong>email your details to</strong> <a class="job_application_email" href="mailto:%1$s%2$s">%1$s</a>', 'wp-job-manager' ) ), esc_html( $apply->email ), '?subject=' . rawurlencode( wp_specialchars_decode( $apply->subject, ENT_QUOTES  ) ) ); ?></p>
```

**Review by fjorgemota — CHANGES_REQUESTED** [review]
Hey there. Thanks for your contribution! And... also sorry for the delay in the review process.

I suggested using a WordPress function to handle the special chars instead of the native PHP function. It's a tiny detail, but it should be better in the long term.

As soon as you apply the change, I'll approve and merge the PR. :tada: 

Thanks again!

**Comment by RafaelKr** [comment]
Thanks for your feedback! I implemented your changes.

**Review by fjorgemota — APPROVED** [review]
Looks good and works well! :tada: 

Thanks again for your contribution! I'll merge it. :smiley:

**Comment by RafaelKr** [comment]
Awesome! :tada: Do you know when the next version will be released?

**Comment by fjorgemota** [comment]
Hey!

> Do you know when the next version will be released?

I expect the next point release to happen in the coming weeks. I still need to work on some issues, and as soon as I fix them, I'll release a new WPJM version. :smiley:

**Comment by RafaelKr** [comment]
Okay, but as long as it's included in the next release, which it is, everything is fine 😉
So it's not overwritten by an update

**Comment by fjorgemota** [comment]
Ah, it'll be included in the next release, for sure. =) 

Thanks again for your contribution. :wink:
