### PR TITLE
Shifting from expired to published extends expiration date

### LINKED ISSUE #974: Adjust Listing Expiration When Changing Status
#### What I Expected To Happen

Changing listing status to "Active" from "Expired"  should actually set the listing as active by adjusting the existing listing expiration based on the original duration set. 

#### What Happened Instead

The listing remains expired because its current expiration date has already passed.

#### Steps to Reproduce the Bug

1. Create a listing with an expiration date in the past.
2. Publish listing. 
3. Set listing to active.

### PR DESCRIPTION
**Pull request by jom**
Fixes #974

#### Changes proposed in this Pull Request:

* Extend expiration date if post is expired and is changed to published

#### Testing instructions:

* See #974

### CODE REVIEW

File: includes/admin/class-wp-job-manager-writepanels.php [hunk 1]
```diff
@@ -585,14 +585,23 @@ public function save_job_listing_data( $post_id, $post ) {
...
+		$expire_date_in_past = $expiry_date && $today_date > $expiry_date;
+		if( $expire_date_in_past ) {
 			remove_action( 'job_manager_save_job_listing', array( $this, 'save_job_listing_data' ), 20, 2 );
-			$job_data = array(
-				'ID'          => $post_id,
-				'post_status' => $post_status,
-			);
-			wp_update_post( $job_data );
+			if (
+				isset( $_POST['post_status'] )
```
Comment (pgk) [inline includes/admin/class-wp-job-manager-writepanels.php]: This can be made more intention-revealing if we extract method (something like `is_job_listing_reactivated` or similar)

File: includes/admin/class-wp-job-manager-writepanels.php [hunk 2]
```diff
@@ -585,14 +585,23 @@ public function save_job_listing_data( $post_id, $post ) {
 		/* Set Post Status To Expired If Already Expired */
 		$expiry_date = get_post_meta( $post_id, '_job_expires', true );
 		$today_date  = date( 'Y-m-d', current_time( 'timestamp' ) );
-		$post_status = $expiry_date && $today_date > $expiry_date ? 'expired' : false;
-		if( $post_status ) {
+		$expire_date_in_past = $expiry_date && $today_date > $expiry_date;
```
Comment (pgk) [inline includes/admin/class-wp-job-manager-writepanels.php]: not necessary, but maybe this could be called `$is_job_listing_expired`

File: includes/admin/class-wp-job-manager-writepanels.php (hunk 1 above)
Comment (jom) [inline includes/admin/class-wp-job-manager-writepanels.php]: Agreed!

**Comment by jom** [comment]
@pgk ✅

**Comment by pgk** [comment]
Sweet as Sugar @jom!
