### PR TITLE
Remove query args from paginate_links urls

### LINKED ISSUE #1912: Mark as Filled action generates incorrect messages with paginated jobs on job dashboard
From https://wordpress.org/support/topic/is-anyone-facing-this-problem-with-filled-or-non-filled-positions/

Screencast: https://streamable.com/i8n7y

Steps to reproduce:

1) Make sure you have enough jobs on your jobs dashboard that they are paginated at least to a page 2.
2) On the jobs dashboard, mark a job as filled; you will get the correct "X has been filled" message.
3) Click on the "2" in the pagination at the bottom of the jobs list.
4) You'll see a random "This position has already been filled." error message at the top.
5) Click again back to page 1, you'll see the same "This position has already been filled." message.
6) Click the "mark as unfilled"; you'll see the correct "X has been marked as not filled." message.
7) Click once again on the "2"; you'll see a random "This position is not filled." message at the top.
8) Click again back to page 1, the same "This position is not filled." message is still there.

These erroneous messages are confusing. :)

### PR DESCRIPTION
**Pull request by JuanchoPestana**
Fixes #1912 

#### Changes proposed in this Pull Request:

* The paginate_links() function adds the url args (from the current url) to each pagination link. The actions (mark as filled, not filled, etc) in the job dashboard were triggered with the url (For example: url/?action=mark_as_filled). The consequences of this were that if you changed the page, the pagination link would carry the "action, job_id, and _wpnonce" parameters to the new page, causing the action to be triggered again; thus, getting the message that the job was already filled/not filled. 
* This PR removes the args from the url for the pagination links so that the actions are not triggered again when changing pages.

#### Testing instructions:

1. Make sure you have enough jobs on your jobs dashboard that they are paginated at least to a page 2.
2. On the jobs dashboard, mark a job as filled; you will get the correct "X has been filled" message.
3. Click on the "2" or the "next arrow" in the pagination at the bottom of the jobs list.
4. You should not see any messages

#### Proposed changelog entry for your changes:
* Remove args from pagination_link urls

### CODE REVIEW

File: includes/class-wp-job-manager-shortcodes.php [hunk 1]
```diff
@@ -272,6 +274,16 @@ public function job_dashboard( $atts ) {
...
 
+	/**
+	 * Filters the url from paginate_links to avoid multiple calls for same action in job dashboard
+	 *
+	 * @param string $link
+	 * @return string
+	 */
+	public function filter_paginate_links( $link ) {
+		return remove_query_arg( [ 'action', 'job_id', '_wpnonce' ], $link );
+	}
```
Comment (alexsanford) [inline includes/class-wp-job-manager-shortcodes.php:285]: I find myself concerned with this again. I had imagined before that this would only be called if a WPJM-related shortcode existed on the page, but looking again I think this would be called on _any_ page that calls the `paginate_links` function. This seems dangerous to me.

Do you think it would make sense to add a condition here to ensure that it only happens on the page(s) we want? E.g. see the `shortcode_action_handler` method. Maybe something like:

```suggestion
	public function filter_paginate_links( $link ) {
		global $post;
		
		if ( is_page() && has_shortcode( $post->post_content, 'job_dashboard' ) ) {
			return remove_query_arg( [ 'action', 'job_id', '_wpnonce' ], $link );
		}
		
		return $link;
	}
```

If so, maybe we could also extract that conditional logic to a private method (assuming we use the same logic as in `shortcode_action_handler`). Maybe `private function is_job_dashboard_page() { ... }`

Comment (JuanchoPestana) [reply includes/class-wp-job-manager-shortcodes.php]: Hey Alex! 
You're totally right! It's a bit too aggressive... Your suggestion works perfectly! I just implemented it...
