### PR TITLE
Move fields from Writepanels

### LINKED ISSUE #2286: Job Submission Fields snippet not working on v.1.36.2
The bug has been reported by a user on this forum thread: https://wordpress.org/support/topic/problem-with-admin-job-submission-form-fields-after-update/#post-15794518

Upon updating the core plugin to v.1.36.2, the script to remove some fields from job submission form in admin (which is based tutorial [here](https://wpjobmanager.com/document/editing-job-submission-fields/)) has stopped working: 

```
add_filter( 'job_manager_job_listing_data_fields', 'custom_job_manager_job_listing_data_fields' );

function custom_job_manager_job_listing_data_fields( $fields ) {

	unset($fields['_company_website']);
	unset($fields['_company_tagline']);
	unset($fields['_company_video']);
	unset($fields['_company_twitter']);
	unset($fields['_company_facebook']);

    return $fields;
```

The script works if rolling the plugin back to previous versions. 

The user came up with a fix that seems to be working: 

```
add_filter( 'job_manager_job_listing_wp_admin_fields', 'custom_job_manager_job_listing_data_fields' );

function custom_job_manager_job_listing_data_fields( $fields ) {

unset($fields['_company_tagline']);
unset($fields['_company_video']);
unset($fields['_company_twitter']);

    return $fields;
}
```  

I'd like to report it here in case you can weigh on it. Thanks!

### PR DESCRIPTION
**Pull request by onubrooks**
Fixes #2286 

### Changes proposed in this Pull Request

* Empty fields array in `WP_Job_Manager_Writepanels` `job_listing_fields()` method.
* Add `_remote_position ` and `_job_salary ` to `WP_Job_Manager_Post_Types::get_job_listing_fields();`

### Testing instructions

* Test that the following snippet works and the fields don't appear on admin:
```
add_filter( 'job_manager_job_listing_data_fields', 'custom_job_manager_job_listing_data_fields' );

function custom_job_manager_job_listing_data_fields( $fields ) {

	unset($fields['_company_website']);
	unset($fields['_company_tagline']);
	unset($fields['_company_video']);
	unset($fields['_company_twitter']);
	unset($fields['_company_facebook']);

    return $fields;
}
```

### CODE REVIEW

**Review by dadish — APPROVED** [review]

File: includes/admin/class-wp-job-manager-writepanels.php [hunk 1]
```diff
@@ -58,67 +58,8 @@ public function job_listing_fields() {
...
-				'priority'    => 10,
-				'description' => __( 'Add a salary field, this field is optional.', 'wp-job-manager' ),
-				'default'     => '',
-			],
-		];
+		$fields = [];
+
 		if ( ! get_option( 'job_manager_enable_salary' ) ) {
 			unset( $fields['_job_salary'] );
 		}
```
Comment (tripflex) [inline includes/admin/class-wp-job-manager-writepanels.php]: Code below here needs to be removed, this is already handled (auth checking) when the fields are looped through.

Comment (tripflex) [reply includes/admin/class-wp-job-manager-writepanels.php]: [[L125-L148]()](https://github.com/Automattic/WP-Job-Manager/pull/2288/files#diff-f785bb6bb9bc6846adf527dc3cdd73dae3866286bb14c8ec2e7d84b1bb3a396cL125-L148)

**Comment by tripflex** [comment]
Thanks @onubrooks there's a few things need to be changed still though, this method should pretty much match what it was before these changes:
https://github.com/Automattic/WP-Job-Manager/blob/1.35.3/includes/admin/class-wp-job-manager-writepanels.php#L55-L129

Mainly these lines:
https://github.com/Automattic/WP-Job-Manager/blob/trunk/includes/admin/class-wp-job-manager-writepanels.php#L125-L140

Setting `job_expires` value is already handled in the code below there

**Comment by tripflex** [comment]
Maybe move this https://github.com/Automattic/WP-Job-Manager/blob/trunk/includes/admin/class-wp-job-manager-writepanels.php#L122-L124 to `show_in_admin` for that field?

**Review by tripflex — APPROVED** [review]

**Review by fjorgemota — CHANGES_REQUESTED** [review]
Looks good overall, but we need to update the test in the file `tests/php/tests/includes/rest-api/test_class.wp-job-manager-job-listings.php` to include the new salary field there too, [as the tests are currently failing right now](https://github.com/Automattic/WP-Job-Manager/runs/7235523887?check_suite_focus=true).

**Comment by onubrooks** [comment]
> Looks good overall, but we need to update the test in the file `tests/php/tests/includes/rest-api/test_class.wp-job-manager-job-listings.php` to include the new salary field there too, [as the tests are currently failing right now](https://github.com/Automattic/WP-Job-Manager/runs/7235523887?check_suite_focus=true).

Fixed in https://github.com/Automattic/WP-Job-Manager/pull/2288/commits/58c9b95a0715d5c2bbdc0a135aa0509bf7321612

**Review by fjorgemota — APPROVED** [review]
Looks good and works well! :tada:
