### PR TITLE
Fix notice dismiss JS dependency error

### LINKED ISSUE #2556: Plugin conflict with Redux Framework
**Describe the bug**
There is a conflict with the plugin Redux Framework. When used on a clean WordPress install and freshly configured Redux Framework (using Twenty-Nineteen theme) text is displayed above the theme options window and a JavaScript error is thrown by WP Job Manager.

**To Reproduce**
- Install & activate Twenty-Nineteen Theme
- Install & activate Redux Framework and include barebones-config.php within Twenty-Nineteen theme functions.php file.
- Within barebones-config.php set config arguments 'menu_type' to 'submenu'. If set to "menu" the bug does not appear.
- Install & activate WP Job Manager
- Go to Appearance > Sample Options
- See error text: 
> Redux will send the debug information found on the WordPress Site Health screen and your Redux config to our secure server. Are you ready to proceed?
> 
> Transmitting data...
>

- Open dev tools and find following in console:
> Uncaught TypeError: t.n(...)() is not a function
    <anonymous> http://testsite-qas.local/testsite/wp-content/plugins/wp-job-manager/assets/dist/js/admin/wpjm-notice-dismiss.js?ver=9efe26399f691357bcd2:1
    <anonymous> http://testsite-qas.local/testsite/wp-content/plugins/wp-job-manager/assets/dist/js/admin/wpjm-notice-dismiss.js?ver=9efe26399f691357bcd2:1

It looks like the JavaScript error is preventing CSS, that should hide the text, from loading properly. WP_DEBUG log is empty and not displaying any errors.

**Screenshots**
Screenshot 2023-08-07 at 09 52-new

**Expected behavior**
The text should not appear at the top of the theme options window.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version:  6.2.2
- WP Job Manager Version:  1.41.0
- PHP Version: 8.0.22
- Other important details: Redux Framework version 4.4.4

### PR DESCRIPTION
**Pull request by yscik**
Fixes #2556

### Changes proposed in this Pull Request

* Fixes a fatal JS error because the `wp-dom-ready` was not being loaded. 

### Testing instructions

* Go to the Job Listings page (`/wp-admin/edit.php?post_type=job_listing`)
* Check in the browser dev tools console that there is no TypeError in `wpjm-notice-dismiss.js`

### CODE REVIEW

File: includes/admin/class-wp-job-manager-admin.php [hunk 1]
```diff
@@ -130,7 +130,7 @@ public function admin_enqueue_scripts() {
 			);
 		}
 
-		WP_Job_manager::register_script( 'job_manager_notice_dismiss', 'js/admin/wpjm-notice-dismiss.js', [], true );
+		WP_Job_manager::register_script( 'job_manager_notice_dismiss', 'js/admin/wpjm-notice-dismiss.js', null, true );
```
Comment (yscik) [inline includes/admin/class-wp-job-manager-admin.php:133]: The `WP_Job_manager::register_script` helper will load the dependencies from `[name].assets.php` generated the webpack script only if this argument is null. Supplying an empty array will instead override that dependency list.

**Review by mikeyarce — APPROVED** [review]
🚢
